### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by jeroenouw** [RandomSoftwareSL/kyanite-cli#2]
@DevDHera nice to see you are using CGX as a base to build your own CLI. 
https://github.com/RandomSoftwareSL/kyanite-cli/blob/657d3e24f0c93a4c845df9e34d34e4fa12ee3dee/src/kyanite.ts#L15

Since version 1.11.0 of CGX, it's moved from OOP to FP which reduced size and did make things simpler. You should try that setup. https://github.com/jeroenouw/cgx/releases

**Comment by DevDHera** [comment]
Thanks @jeroenouw for pointing me for the FP road. I created the CLI with the help of your article named [Create Your Own Advanced CLI - With TypeScript](https://levelup.gitconnected.com/create-your-own-advanced-cli-with-typescript-5868ae3df397). 

I will convert the CLI from OOP to FP in the meantime 😊.
